name: Deploy Discord Bot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/Discord_mriamys
            git pull origin master
            source /root/shared_env/bin/activate
            pip install -r requirements.txt
            systemctl restart mriamys
